### ISSUE TITLE
How do we check which achievement/how the checkmark is given?

### ISSUE THREAD

**Issue by Azurealistic** [bourgeoisor/xivtodo#15]
Hi, so for example I have all these quests done and what not:

![image](https://user-images.githubusercontent.com/5000092/145495903-a2469512-63e1-4cc1-8972-3e17ce0c51e8.png)

And it doesn't pick them up (this was pre-ew) my question is how do I know what quest triggers the checkmark/why isn't it triggering. Can you add a tooltip or similar to explain the question mark ones?

**Comment by bourgeoisor** [comment]
Hi! Thank you for your feedback. I understand that it's not super intuitive and I'm very opened to any ideas on how to make this experience better.

I have a manually-created "spreadsheet" (https://github.com/bourgeoisor/xivtodo/blob/main/src/assets/db.json) -- it's just an export from a Google Sheets --which contains a list of the encounters / quests and what achievement IDs marks them either as "not cleared", or "might have cleared but not certain", or "have cleared".

Some encounters and quests are really easy to track since they're 1:1 with a specific achievements (some examples include most Extreme trials and the combat job quests -- except for BLU which is an exception to this rule).

Some encounters and quests are more difficult to track since they don't map 1:1 with an achievements and instead I need to do some deduction based on _other_ achievements (a good example is Ultima (Extreme). There aren't any achievements for clearing it, but there _is_ an achievement for clearing Binding Coils (Savage) and clearing _that_ implies clearing Ultima (Extreme) since it's a prerequisite, so I put two-and-two together and mark both as cleared at the same time. Else, I mark it as a (?), unless the user hasn't cleared 2.0 in which case it shows as not-cleared).

Some encounters and quests are impossible to track based on achievements at all; crafting quests are in that category, since there are no achievements related to the crafting quests.

So there are two problems here:
- How to properly convey to the user that some encounters and quests are listed for completion sake, but will never be marked as "cleared" (for the reasons listed above); and
- How to properly convey that a (?) doesn't inherently mean that the encounter or quest hasn't been cleared by the user, just that I don't have enough information from the achievements to deduce this;

I've been ongoing brainstorming for a while but this is one of my difficult topics. Opened to any suggestions or feedback!

**Comment by Darklord6229** [comment]
What if it was made that when you click on 
![image](https://user-images.githubusercontent.com/1007659/147033811-caafb895-117c-4b68-8ae3-926ad88893db.png)
the circles it does a drop down or popup that shows the logic or achievements you used to determine that mark to be green? One could also add local cache or if you do indeed add server side storage for char profiles to allow us to manually override things that we know we completed?

**Comment by bourgeoisor** [comment]
I like both of those ideas! For allowing manually checking things off, it's already planned (at the same time as https://github.com/bourgeoisor/xivtodo/issues/13), though between work and Endwalker I haven't had much opportunity to work on it. It's my big goal in the new year.

**Comment by bourgeoisor** [comment]
Manual tracking is now live! You can click on encounters or questlines that are (?) to mark them as cleared manually.

Backend: https://github.com/bourgeoisor/xivtodo/commit/13fa805c6ab48f8304c09a8f8eb7da2b42c2aa78
Frontend: https://github.com/bourgeoisor/xivtodo/commit/a52ba63b1e55c9ead7779a0bd0c2fe7124bffd0e

Screenshot:
![image](https://user-images.githubusercontent.com/3271352/173238910-b0a59786-12cf-492c-ac06-b02b280791f3.png)
